### ISSUE TITLE
Override and virtual keyword issue

### ISSUE THREAD

**Issue by mporw12** [PatrickAlphaC/storage-factory-fcc#3]
```javascript
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./SimpleStorage.sol";

contract ExtraStorage is SimpleStorage {
    function store(uint256 _favoriteNumber) public override {
        favoriteNumber = _favoriteNumber + 5;
    }
}
```

This code does not compile and the error says that: 

![Screen Shot 2022-06-01 at 2 28 56 PM](https://user-images.githubusercontent.com/101594741/171486315-91a3db6d-c634-486c-9fb9-a6bf7fad48ed.png)

**Comment by PatrickAlphaC** [comment]
Could you please copy-paste the error as opposed to using a screenshot? Thank you. 

You need to add `virtual` to the store function in the `SimpleStorage` contract.
